 #need to backup files first
 
- name: ensure required packages are installed
  yum: name={{ item }} state=present
  with_items:
    - sssd
    - krb5-workstation
    - samba-common
    - authconfig
    - oddjob-mkhomedir
    - adcli
- name: insert sssd.conf 
  template: src=sssd.conf.j2 dest=/etc/sssd/sssd.conf backup=yes mode=600

- name: insert krb5.conf
  template: src=krb5.conf.j2 dest=/etc/krb5.conf backup=yes

- name: insert smb.conf
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf backup=yes


- name: enabling sssd authentication via authconfig
  command: authconfig --enablesssd --enablesssdauth --enablemkhomedir --update

#This depends on the computer account being precreated and having been reset, which makes the computer password the same as the SAMaccount name. 
- name: performing AD join
  shell: OTP=$(hostname -s) && adcli join --one-time-password=$OTP


- name: starting required services 
  service: name={{ item }} state=started enabled=yes
  with_items: 
    - sssd
    - oddjobd
